### ISSUE TITLE
Unfortunately, this no longer works for Remeha.

### ISSUE THREAD

**Issue by MarAlze** [Kleinrotti/py-senertec#1]
Unfortunately, this no longer works for Remeha.

As of 01.07. Senertec has locked out the Remeha systems.

**Comment by Kleinrotti** [comment]
I can't confirm that. My Remeha device is still working in Dachsportal2 right now.
Have you tried to login to Dachsportal2 directly in the Browser?

**Comment by MarAlze** [comment]
Right. 

Now it works again. 
It didn't work for a few hours this morning on the DachsPortal2 page with the error message that the user was not found.
On the KWK-Connect page it worked.


Here are a few more lines for the productGroups.json file e.g. cable break detection outdoor temperature sensor.
"dachs08": [
        "CM240",
        "CM210",
        "CP010",
        "CP900",
        "CP910",
        "CP920",
        "CP930",
        "CP940"
