### ISSUE TITLE
Add source of API documentation used by the python lib

### ISSUE THREAD

**Issue by mulles** [Kleinrotti/py-senertec#14]
Did you reverse engineer something or is there  documentation about the websocket (wss://dachsconnect.senertec.com/ws) used within the lib? Do you use an official API provided by senerectec for [https://dachsconnect.senertec.com/)]( https://dachsconnect.senertec.com/) ? 

I am currently developing a programm which calculated how much money you will get per month from grid provider, based on energy prices on EPEX energy exchange and production scrapped with help of selenium python lib from [dachsportal.senertec.com](dachsportal.senertec.com).

The programm will be publised under open source software soon and maybe I can use a defined API instead of scrapping from a web page?

**Comment by Kleinrotti** [comment]
Unfortunately there is no official API available from Senertec. I had to "reverse engineer" it.

**Comment by mulles** [comment]
Good Job :) I will close this issue now :)
